from fastapi import FastAPI
import joblib
from pydantic import BaseModel
from typing import Optional
import pandas as pd
import uvicorn

def downcasting(df: pd.DataFrame, id: str = None) -> pd.DataFrame:
    """Downcast data types of all features where possible to improve memory efficiency and boost processing speed."""
    df_copy = df.copy()
    columns_to_downcast = df_copy.columns.drop(id) if id else df_copy.columns
    for column in columns_to_downcast:
        if df_copy[column].dtype == "float64":
            df_copy[column] = pd.to_numeric(df_copy[column], downcast="float")
        elif df_copy[column].dtype == "int64":
            df_copy[column] = pd.to_numeric(df_copy[column], downcast="integer")
        elif df_copy[column].nunique() == 2 and df_copy[column].dtype == "object":
            df_copy[column], _ = pd.factorize(df_copy[column])
            df_copy[column] = df_copy[column].astype("int8")
        elif df_copy[column].dtype == "object":
            df_copy[column] = df_copy[column].astype("category")
    return df_copy

with open("model_for_deployment.pkl", "rb") as f:
    model = joblib.load(f)

app = FastAPI()


class InputData(BaseModel):
    NAME_CONTRACT_TYPE: Optional[int]
    CODE_GENDER: Optional[str]
    AMT_CREDIT: Optional[float]
    AMT_ANNUITY: Optional[float]
    AMT_GOODS_PRICE: Optional[float]
    NAME_EDUCATION_TYPE: Optional[str]
    NAME_FAMILY_STATUS: Optional[str]
    REGION_POPULATION_RELATIVE: Optional[float]
    DAYS_BIRTH: Optional[int]
    DAYS_EMPLOYED: Optional[int]
    DAYS_REGISTRATION: Optional[float]
    DAYS_ID_PUBLISH: Optional[int]
    OWN_CAR_AGE: Optional[float]
    FLAG_WORK_PHONE: Optional[int]
    OCCUPATION_TYPE: Optional[str]
    CNT_FAM_MEMBERS: Optional[float]
    REGION_RATING_CLIENT: Optional[int]
    HOUR_APPR_PROCESS_START: Optional[int]
    REG_CITY_NOT_LIVE_CITY: Optional[int]
    EXT_SOURCE_1: Optional[float]
    EXT_SOURCE_2: Optional[float]
    EXT_SOURCE_3: Optional[float]
    APARTMENTS_AVG: Optional[float]
    BASEMENTAREA_AVG: Optional[float]
    YEARS_BUILD_AVG: Optional[float]
    COMMONAREA_AVG: Optional[float]
    ENTRANCES_AVG: Optional[float]
    FLOORSMAX_AVG: Optional[float]
    LANDAREA_AVG: Optional[float]
    LIVINGAREA_AVG: Optional[float]
    NONLIVINGAREA_AVG: Optional[float]
    LIVINGAPARTMENTS_MODE: Optional[float]
    FONDKAPREMONT_MODE: Optional[str]
    DEF_60_CNT_SOCIAL_CIRCLE: Optional[float]
    DAYS_LAST_PHONE_CHANGE: Optional[float]
    FLAG_DOCUMENT_3: Optional[int]
    DEBT_TO_INCOME_RATIO: Optional[float]
    CREDIT_TERM_TO_AGE_RATIO: Optional[float]
    POPULATION_DENSITY_RISK: Optional[float]
    CREDIT_TO_ANNUITY_RATIO: Optional[float]
    ANNUITY_TO_INCOME_RATIO: Optional[float]
    DAYS_BIRTH_TO_ANNUITY_RATIO: Optional[float]
    DAYS_BIRTH_TO_CREDIT_RATIO: Optional[float]
    DAYS_BIRTH_TO_INCOME_RATIO: Optional[float]
    DAYS_EMPLOYED_TO_ANNUITY_RATIO: Optional[float]
    DAYS_EMPLOYED_TO_CREDIT_RATIO: Optional[float]
    DAYS_EMPLOYED_TO_INCOME_RATIO: Optional[float]
    DAYS_EMPLOYED_TO_GOODS_PRICE_RATIO: Optional[float]
    ANNUITY_TO_GOODS_RATIO: Optional[float]
    CAR_AGE_TO_AGE_RATIO: Optional[float]
    CREDIT_TO_GOODS_RATIO: Optional[float]
    DAYS_BIRTH_TO_OWN_CAR_AGE: Optional[float]
    GOODS_PRICE_TO_DAYS_BIRTH: Optional[float]
    SK_ID_PREV_COUNT_CONSUMER_LOANS: Optional[float]
    AMT_ANNUITY_MEAN_CONSUMER_LOANS: Optional[float]
    AMT_APPLICATION_MEAN_CONSUMER_LOANS: Optional[float]
    AMT_APPLICATION_MEAN_REVOLVING_LOANS: Optional[float]
    AMT_CREDIT_MEAN_CONSUMER_LOANS: Optional[float]
    AMT_GOODS_PRICE_MEAN_CONSUMER_LOANS: Optional[float]
    HOUR_APPR_PROCESS_START_MEAN_CASH_LOANS: Optional[float]
    HOUR_APPR_PROCESS_START_MEAN_CONSUMER_LOANS: Optional[float]
    DAYS_DECISION_MEAN_CASH_LOANS: Optional[float]
    DAYS_DECISION_MEAN_CONSUMER_LOANS: Optional[float]
    DAYS_DECISION_MEAN_REVOLVING_LOANS: Optional[float]
    CNT_PAYMENT_MEAN_CASH_LOANS: Optional[float]
    DAYS_LAST_DUE_1ST_VERSION_MEAN_CASH_LOANS: Optional[float]
    DAYS_LAST_DUE_1ST_VERSION_MEAN_CONSUMER_LOANS: Optional[float]
    DAYS_LAST_DUE_MEAN_CASH_LOANS: Optional[float]
    DAYS_LAST_DUE_MEAN_CONSUMER_LOANS: Optional[float]
    DAYS_TERMINATION_MEAN_CASH_LOANS: Optional[float]
    DOWN_PAYMENT_TO_CREDIT_RATIO_MEAN_CONSUMER_LOANS: Optional[float]
    ANNUITY_TO_CREDIT_RATIO_MEAN_CASH_LOANS: Optional[float]
    GOODS_PRICE_TO_CREDIT_RATIO_MEAN_CASH_LOANS: Optional[float]
    GOODS_PRICE_TO_CREDIT_RATIO_MEAN_REVOLVING_LOANS: Optional[float]
    PAYMENT_TO_GOODS_PRICE_RATIO_MEAN_CONSUMER_LOANS: Optional[float]
    DECISION_TO_FIRST_DUE_RATIO_MEAN_CASH_LOANS: Optional[float]
    DECISION_TO_FIRST_DUE_RATIO_MEAN_CONSUMER_LOANS: Optional[float]
    FIRST_DUE_TO_LAST_DUE_RATIO_MEAN_CASH_LOANS: Optional[float]
    INSTALLMENTS_TO_CREDIT_RATIO_MEAN_CASH_LOANS: Optional[float]
    INSTALLMENTS_TO_CREDIT_RATIO_MEAN_CONSUMER_LOANS: Optional[float]
    DECISION_TO_TERMINATION_RATIO_MEAN_CASH_LOANS: Optional[float]
    FIRST_DRAWING_TO_FIRST_DUE_RATIO_MEAN_CASH_LOANS: Optional[float]
    TERMINATION_TO_LAST_DUE_RATIO_MEAN_CONSUMER_LOANS: Optional[float]
    APPLICATION_TO_ANNUITY_RATIO_MEAN_CASH_LOANS: Optional[float]
    APPLICATION_TO_ANNUITY_RATIO_MEAN_REVOLVING_LOANS: Optional[float]
    GOODS_PRICE_TO_CREDIT_TERM_RATIO_MEAN_CASH_LOANS: Optional[float]
    GOODS_PRICE_TO_CREDIT_TERM_RATIO_MEAN_CONSUMER_LOANS: Optional[float]
    AMT_ANNUITY_MIN_x: Optional[float]
    AMT_ANNUITY_MAX_x: Optional[float]
    AMT_APPLICATION_MEAN: Optional[float]
    AMT_APPLICATION_MAX: Optional[float]
    AMT_CREDIT_MIN: Optional[float]
    AMT_CREDIT_MAX: Optional[float]
    AMT_DOWN_PAYMENT_MIN: Optional[float]
    AMT_GOODS_PRICE_MIN: Optional[float]
    HOUR_APPR_PROCESS_START_MEAN: Optional[float]
    RATE_DOWN_PAYMENT_MIN: Optional[float]
    RATE_DOWN_PAYMENT_MAX: Optional[float]
    DAYS_DECISION_MEAN: Optional[float]
    DAYS_DECISION_MIN: Optional[float]
    DAYS_DECISION_MAX: Optional[float]
    CNT_PAYMENT_MEAN: Optional[float]
    CNT_PAYMENT_MAX: Optional[float]
    DAYS_FIRST_DUE_MEAN: Optional[float]
    DAYS_FIRST_DUE_MIN: Optional[float]
    DAYS_LAST_DUE_1ST_VERSION_MEAN: Optional[float]
    DAYS_LAST_DUE_1ST_VERSION_MIN: Optional[float]
    DAYS_LAST_DUE_1ST_VERSION_MAX: Optional[float]
    DAYS_LAST_DUE_MIN: Optional[float]
    DAYS_LAST_DUE_MAX: Optional[float]
    DAYS_TERMINATION_MIN: Optional[float]
    DAYS_TERMINATION_MAX: Optional[float]
    CREDIT_TO_APPLICATION_RATIO_MEAN: Optional[float]
    CREDIT_TO_APPLICATION_RATIO_MIN: Optional[float]
    CREDIT_TO_APPLICATION_RATIO_MAX: Optional[float]
    DOWN_PAYMENT_TO_CREDIT_RATIO_MEAN: Optional[float]
    DOWN_PAYMENT_TO_CREDIT_RATIO_MIN: Optional[float]
    ANNUITY_TO_CREDIT_RATIO_MEAN_x: Optional[float]
    ANNUITY_TO_CREDIT_RATIO_MAX_x: Optional[float]
    GOODS_PRICE_TO_CREDIT_RATIO_MEAN: Optional[float]
    GOODS_PRICE_TO_CREDIT_RATIO_MIN: Optional[float]
    GOODS_PRICE_TO_CREDIT_RATIO_MAX: Optional[float]
    PAYMENT_TO_GOODS_PRICE_RATIO_MEAN: Optional[float]
    PAYMENT_TO_GOODS_PRICE_RATIO_MIN: Optional[float]
    DOWN_PAYMENT_TO_GOODS_PRICE_RATIO_MEAN: Optional[float]
    DOWN_PAYMENT_TO_GOODS_PRICE_RATIO_MAX: Optional[float]
    DECISION_TO_FIRST_DUE_RATIO_MEAN: Optional[float]
    DECISION_TO_FIRST_DUE_RATIO_MIN: Optional[float]
    FIRST_DRAWING_TO_TERMINATION_RATIO_MEAN: Optional[float]
    FIRST_DRAWING_TO_TERMINATION_RATIO_MIN: Optional[float]
    FIRST_DUE_TO_LAST_DUE_RATIO_MEAN: Optional[float]
    FIRST_DUE_TO_LAST_DUE_RATIO_MAX: Optional[float]
    INSTALLMENTS_TO_CREDIT_RATIO_MEAN: Optional[float]
    DECISION_TO_TERMINATION_RATIO_MIN: Optional[float]
    DECISION_TO_TERMINATION_RATIO_MAX: Optional[float]
    FIRST_DRAWING_TO_FIRST_DUE_RATIO_MIN: Optional[float]
    TERMINATION_TO_LAST_DUE_RATIO_MEAN: Optional[float]
    TERMINATION_TO_LAST_DUE_RATIO_MIN: Optional[float]
    TERMINATION_TO_LAST_DUE_RATIO_MAX: Optional[float]
    APPLICATION_TO_ANNUITY_RATIO_MEAN: Optional[float]
    APPLICATION_TO_ANNUITY_RATIO_MIN: Optional[float]
    GOODS_PRICE_TO_CREDIT_TERM_RATIO_MEAN: Optional[float]
    GOODS_PRICE_TO_CREDIT_TERM_RATIO_MIN: Optional[float]
    GOODS_PRICE_TO_CREDIT_TERM_RATIO_MAX: Optional[float]
    NAME_CONTRACT_STATUS_MODE_x: Optional[str]
    CODE_REJECT_REASON_MODE: Optional[str]
    NAME_GOODS_CATEGORY_MODE: Optional[str]
    NAME_SELLER_INDUSTRY_MODE: Optional[str]
    PRODUCT_COMBINATION_MODE: Optional[str]
    DAYS_CREDIT_MEAN: Optional[float]
    DAYS_CREDIT_MIN: Optional[float]
    DAYS_CREDIT_MAX: Optional[float]
    DAYS_CREDIT_ENDDATE_MEAN: Optional[float]
    DAYS_CREDIT_ENDDATE_MIN: Optional[float]
    DAYS_CREDIT_ENDDATE_MAX: Optional[float]
    DAYS_ENDDATE_FACT_MEAN: Optional[float]
    DAYS_ENDDATE_FACT_MAX: Optional[float]
    AMT_CREDIT_MAX_OVERDUE_MEAN: Optional[float]
    AMT_CREDIT_SUM_MIN: Optional[float]
    AMT_CREDIT_SUM_DEBT_MEAN: Optional[float]
    AMT_CREDIT_SUM_DEBT_MIN: Optional[float]
    AMT_CREDIT_SUM_LIMIT_MEAN: Optional[float]
    AMT_CREDIT_SUM_LIMIT_MAX: Optional[float]
    DAYS_CREDIT_UPDATE_MEAN: Optional[float]
    DAYS_CREDIT_UPDATE_MIN: Optional[float]
    CREDIT_OVERDUE_RATIO_MAX: Optional[float]
    MAX_OVERDUE_TO_CREDIT_RATIO_MEAN: Optional[float]
    MAX_OVERDUE_TO_CREDIT_RATIO_MAX: Optional[float]
    CREDIT_DURATION_RATIO_MEAN: Optional[float]
    CREDIT_DURATION_RATIO_MIN: Optional[float]
    CREDIT_DURATION_RATIO_MAX: Optional[float]
    DAYS_END_TO_DURATION_RATIO_MEAN: Optional[float]
    DAYS_END_TO_DURATION_RATIO_MIN: Optional[float]
    CREDIT_UPDATE_DURATION_RATIO_MEAN: Optional[float]
    CREDIT_UPDATE_DURATION_RATIO_MAX: Optional[float]
    MAX_STATUS_MEAN: Optional[float]
    CONSECUTIVE_ZEROS_BEFORE_C_MEAN: Optional[float]
    CONSECUTIVE_ZEROS_BEFORE_C_MIN: Optional[float]
    ZERO_MEAN: Optional[float]
    ZERO_MIN: Optional[float]
    ONE_MAX: Optional[float]
    THREE_MAX: Optional[float]
    FOUR_MEAN: Optional[float]
    C_MAX: Optional[float]
    X_MEAN: Optional[float]
    CREDIT_TYPE_MODE: Optional[str]
    LAST_STATUS_AT_MOST_RECENT_MONTH_MODE: Optional[str]
    RECENT_STATUS_MODE_MODE: Optional[str]
    MONTHS_BALANCE_MAX: Optional[float]
    CNT_INSTALMENT_MIN: Optional[float]
    CNT_INSTALMENT_FUTURE_MEAN: Optional[float]
    SK_DPD_DEF_MEAN: Optional[float]
    INSTALMENTS_COMPLETION_RATIO_MEAN: Optional[float]
    DPD_DEF_TO_DPD_RATIO_MEAN: Optional[float]
    MONTHLY_DELAY_RATIO_MEAN: Optional[float]
    RECENT_CNT_INSTALMENT_MEAN: Optional[float]
    RECENT_CNT_INSTALMENT_FUTURE_MEAN: Optional[float]
    RECENT_SK_DPD_DEF_MEAN: Optional[float]
    RECENT_INSTALMENTS_COMPLETION_RATIO_MEAN: Optional[float]
    RECENT_AVG_DPD_DEF_PER_INSTALMENT_MEAN: Optional[float]
    RECENT_MONTHLY_DELAY_RATIO_MEAN: Optional[float]
    RECENT_ON_TIME_INSTALMENTS_RATIO_MEAN: Optional[float]
    TOTAL_NUM_INSTALLMENTS: Optional[float]
    LATE_PAYMENT_RATIO: Optional[float]
    MEAN_NORMALIZED_DAYS_LATE: Optional[float]
    MEAN_AMOUNT_DIFFERENCE: Optional[float]
    LATE_PAYMENTS_FIRST_5: Optional[float]
    NUM_INSTALMENT_VERSIONS: Optional[float]
    CARD_AMT_CREDIT_LIMIT_ACTUAL_MEAN: Optional[float]
    CARD_AMT_PAYMENT_CURRENT_MEAN: Optional[float]
    CARD_CNT_DRAWINGS_ATM_CURRENT_MEAN: Optional[float]
    CARD_CNT_DRAWINGS_CURRENT_MEAN: Optional[float]
    CARD_CNT_INSTALMENT_MATURE_CUM_MEAN: Optional[float]
    CARD_BALANCE_TO_CREDIT_LIMIT_RATIO_MAX: Optional[float]
    CARD_MIN_INSTALLMENT_TO_TOTAL_PAYMENT_RATIO_MEAN: Optional[float]
    CARD_TOTAL_RECEIVABLE_TO_CREDIT_LIMIT_RATIO_MEAN: Optional[float]
    CARD_TOTAL_RECEIVABLE_TO_CREDIT_LIMIT_RATIO_MAX: Optional[float]
    CARD_RECENT_AMT_CREDIT_LIMIT_ACTUAL_MEAN: Optional[float]
    CARD_RECENT_AMT_DRAWINGS_ATM_CURRENT_MEAN: Optional[float]
    CARD_RECENT_AMT_PAYMENT_CURRENT_MEAN: Optional[float]
    CARD_RECENT_CNT_DRAWINGS_ATM_CURRENT_MEAN: Optional[float]
    CARD_RECENT_CNT_DRAWINGS_CURRENT_MEAN: Optional[float]
    CARD_RECENT_CNT_INSTALMENT_MATURE_CUM_MEAN: Optional[float]
    CARD_RECENT_BALANCE_TO_CREDIT_LIMIT_RATIO_MEAN: Optional[float]
    CARD_RECENT_MIN_INSTALLMENT_TO_TOTAL_PAYMENT_RATIO_MEAN: Optional[float]
    CARD_RECENT_RECEIVABLE_TO_CREDIT_LIMIT_RATIO_MEAN: Optional[float]
    CARD_RECENT_TOTAL_RECEIVABLE_TO_CREDIT_LIMIT_RATIO_MEAN: Optional[float]


@app.post("/predict/")
def predict(data: InputData):
    input_data = downcasting(pd.DataFrame([data.dict()]))
    prediction = model.predict(input_data)
    probability = model.predict_proba(input_data)[0]
    if int(prediction[0]) == 0:
        return f"Applicant will be able to pay on time, with probability of {probability[0]:.2f}"
    else:
        return f"Applicant will not be able to pay on time, with probability of {probability[1]:.2f}"

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8080)